"""init schema

Revision ID: ca9871597eb1
Revises: 
Create Date: 2026-05-10 09:29:53.384063+08:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ca9871597eb1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_hours'))
    )
    op.create_index(op.f('ix_business_hours_weekday'), 'business_hours', ['weekday'], unique=False)
    op.create_table('card_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('TIME', 'TIMES', 'STORED_VALUE', 'PERSONAL_TRAINING', name='cardkind', native_enum=False), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('total_times', sa.Integer(), nullable=True),
    sa.Column('stored_value_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_types'))
    )
    op.create_index(op.f('ix_card_types_kind'), 'card_types', ['kind'], unique=False)
    op.create_index(op.f('ix_card_types_name'), 'card_types', ['name'], unique=True)
    op.create_table('club_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_settings'))
    )
    op.create_table('course_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_categories'))
    )
    op.create_index(op.f('ix_course_categories_name'), 'course_categories', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name=op.f('fk_departments_parent_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ENDED', name='campaignstatus', native_enum=False), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_campaigns'))
    )
    op.create_index(op.f('ix_marketing_campaigns_status'), 'marketing_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_title'), 'marketing_campaigns', ['title'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=160), nullable=False),
    sa.Column('component', sa.String(length=160), nullable=True),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('permission_code', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], name=op.f('fk_menus_parent_id_menus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menus'))
    )
    op.create_index(op.f('ix_menus_path'), 'menus', ['path'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['course_categories.id'], name=op.f('fk_courses_category_id_course_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_table('role_menus',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name=op.f('fk_role_menus_menu_id_menus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_menus_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id', name=op.f('pk_role_menus'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_logs'))
    )
    op.create_index(op.f('ix_login_logs_username'), 'login_logs', ['username'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_notifications_published_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_target_type'), 'notifications', ['target_type'], unique=False)
    op.create_index(op.f('ix_notifications_title'), 'notifications', ['title'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=12), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operation_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=80), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_staff_department_id_departments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_index(op.f('ix_staff_mobile'), 'staff', ['mobile'], unique=False)
    op.create_index(op.f('ix_staff_name'), 'staff', ['name'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('specialties', sa.String(length=255), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_coaches_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaches'))
    )
    op.create_index(op.f('ix_coaches_mobile'), 'coaches', ['mobile'], unique=False)
    op.create_index(op.f('ix_coaches_name'), 'coaches', ['name'], unique=False)
    op.create_table('course_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('waitlisted_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'FINISHED', name='schedulestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_course_schedules_coach_id_coaches')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_schedules_course_id_courses')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_course_schedules_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_schedules'))
    )
    op.create_index(op.f('ix_course_schedules_course_id'), 'course_schedules', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_schedules_start_time'), 'course_schedules', ['start_time'], unique=False)
    op.create_index(op.f('ix_course_schedules_status'), 'course_schedules', ['status'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('member_no', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.Enum('UNKNOWN', 'MALE', 'FEMALE', name='gender', native_enum=False), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NORMAL', 'FROZEN', 'EXPIRED', 'LOST', 'LEAD', name='memberstatus', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('consultant_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_members_coach_id_coaches')),
    sa.ForeignKeyConstraint(['consultant_id'], ['staff.id'], name=op.f('fk_members_consultant_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members'))
    )
    op.create_index(op.f('ix_members_member_no'), 'members', ['member_no'], unique=True)
    op.create_index(op.f('ix_members_mobile'), 'members', ['mobile'], unique=True)
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_table('bracelet_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('bracelet_no', sa.String(length=50), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('BORROWED', 'RETURNED', name='braceletstatus', native_enum=False), nullable=False),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_bracelet_records_handled_by_id_users')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_bracelet_records_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bracelet_records'))
    )
    op.create_index(op.f('ix_bracelet_records_borrowed_at'), 'bracelet_records', ['borrowed_at'], unique=False)
    op.create_index(op.f('ix_bracelet_records_bracelet_no'), 'bracelet_records', ['bracelet_no'], unique=False)
    op.create_index(op.f('ix_bracelet_records_member_id'), 'bracelet_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_bracelet_records_status'), 'bracelet_records', ['status'], unique=False)
    op.create_table('campaign_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], name=op.f('fk_campaign_registrations_campaign_id_marketing_campaigns')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_campaign_registrations_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_registrations'))
    )
    op.create_index(op.f('ix_campaign_registrations_campaign_id'), 'campaign_registrations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_registrations_member_id'), 'campaign_registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_campaign_registrations_mobile'), 'campaign_registrations', ['mobile'], unique=False)
    op.create_table('member_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('card_type_id', sa.Integer(), nullable=False),
    sa.Column('card_no', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.Enum('TIME', 'TIMES', 'STORED_VALUE', 'PERSONAL_TRAINING', name='cardkind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'EXPIRED', 'REFUNDED', name='cardstatus', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remaining_times', sa.Integer(), nullable=True),
    sa.Column('balance_cents', sa.Integer(), nullable=True),
    sa.Column('frozen_from', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_type_id'], ['card_types.id'], name=op.f('fk_member_cards_card_type_id_card_types')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_member_cards_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_cards'))
    )
    op.create_index(op.f('ix_member_cards_card_no'), 'member_cards', ['card_no'], unique=True)
    op.create_index(op.f('ix_member_cards_end_date'), 'member_cards', ['end_date'], unique=False)
    op.create_index(op.f('ix_member_cards_kind'), 'member_cards', ['kind'], unique=False)
    op.create_index(op.f('ix_member_cards_member_id'), 'member_cards', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_cards_status'), 'member_cards', ['status'], unique=False)
    op.create_table('member_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_member_feedback_handled_by_id_users')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_member_feedback_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_feedback'))
    )
    op.create_index(op.f('ix_member_feedback_member_id'), 'member_feedback', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_feedback_status'), 'member_feedback', ['status'], unique=False)
    op.create_table('member_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_member_followups_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_member_followups_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_followups'))
    )
    op.create_index(op.f('ix_member_followups_member_id'), 'member_followups', ['member_id'], unique=False)
    op.create_table('member_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=80), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('fitness_goal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_member_profiles_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_profiles')),
    sa.UniqueConstraint('member_id', name=op.f('uq_member_profiles_member_id'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('paid_amount_cents', sa.Integer(), nullable=False),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_orders_handled_by_id_users')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_orders_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_member_id'), 'orders', ['member_id'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('body_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_training_records_coach_id_coaches')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_training_records_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_records'))
    )
    op.create_index(op.f('ix_training_records_member_id'), 'training_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_training_records_record_date'), 'training_records', ['record_date'], unique=False)
    op.create_table('card_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_card_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('OPEN', 'RENEW', 'RECHARGE', 'CONSUME', 'FREEZE', 'UNFREEZE', 'REFUND', 'TRANSFER', name='cardtransactiontype', native_enum=False), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('times_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after_cents', sa.Integer(), nullable=True),
    sa.Column('times_after', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_card_id'], ['member_cards.id'], name=op.f('fk_card_transactions_member_card_id_member_cards')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_card_transactions_member_id_members')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_card_transactions_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_transactions'))
    )
    op.create_index(op.f('ix_card_transactions_member_card_id'), 'card_transactions', ['member_card_id'], unique=False)
    op.create_index(op.f('ix_card_transactions_member_id'), 'card_transactions', ['member_id'], unique=False)
    op.create_index(op.f('ix_card_transactions_transaction_type'), 'card_transactions', ['transaction_type'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('member_card_id', sa.Integer(), nullable=True),
    sa.Column('checkin_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CHECKED_OUT', name='checkinstatus', native_enum=False), nullable=False),
    sa.Column('bracelet_no', sa.String(length=50), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_checkins_handled_by_id_users')),
    sa.ForeignKeyConstraint(['member_card_id'], ['member_cards.id'], name=op.f('fk_checkins_member_card_id_member_cards')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_checkins_member_id_members')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins'))
    )
    op.create_index(op.f('ix_checkins_bracelet_no'), 'checkins', ['bracelet_no'], unique=False)
    op.create_index(op.f('ix_checkins_checkin_time'), 'checkins', ['checkin_time'], unique=False)
    op.create_index(op.f('ix_checkins_member_id'), 'checkins', ['member_id'], unique=False)
    op.create_index(op.f('ix_checkins_status'), 'checkins', ['status'], unique=False)
    op.create_table('course_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('member_card_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELLED', 'ATTENDED', 'WAITLISTED', name='bookingstatus', native_enum=False), nullable=False),
    sa.Column('booked_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_id'], ['users.id'], name=op.f('fk_course_bookings_booked_by_id_users')),
    sa.ForeignKeyConstraint(['member_card_id'], ['member_cards.id'], name=op.f('fk_course_bookings_member_card_id_member_cards')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_course_bookings_member_id_members')),
    sa.ForeignKeyConstraint(['schedule_id'], ['course_schedules.id'], name=op.f('fk_course_bookings_schedule_id_course_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_bookings'))
    )
    op.create_index(op.f('ix_course_bookings_member_id'), 'course_bookings', ['member_id'], unique=False)
    op.create_index(op.f('ix_course_bookings_schedule_id'), 'course_bookings', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_course_bookings_status'), 'course_bookings', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_no', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('paid_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.ForeignKeyConstraint(['paid_by_id'], ['users.id'], name=op.f('fk_payments_paid_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_no'), 'payments', ['payment_no'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('personal_training_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('remaining_sessions', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_personal_training_packages_coach_id_coaches')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_personal_training_packages_member_id_members')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_personal_training_packages_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_training_packages'))
    )
    op.create_index(op.f('ix_personal_training_packages_member_id'), 'personal_training_packages', ['member_id'], unique=False)
    op.create_index(op.f('ix_personal_training_packages_status'), 'personal_training_packages', ['status'], unique=False)
    op.create_table('course_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['course_bookings.id'], name=op.f('fk_course_attendance_booking_id_course_bookings')),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_course_attendance_handled_by_id_users')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_course_attendance_member_id_members')),
    sa.ForeignKeyConstraint(['schedule_id'], ['course_schedules.id'], name=op.f('fk_course_attendance_schedule_id_course_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_attendance')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_course_attendance_booking_id'))
    )
    op.create_index(op.f('ix_course_attendance_attended_at'), 'course_attendance', ['attended_at'], unique=False)
    op.create_index(op.f('ix_course_attendance_member_id'), 'course_attendance', ['member_id'], unique=False)
    op.create_index(op.f('ix_course_attendance_schedule_id'), 'course_attendance', ['schedule_id'], unique=False)
    op.create_table('personal_training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'CANCELLED', name='personaltrainingsessionstatus', native_enum=False), nullable=False),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('training_record_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_personal_training_sessions_coach_id_coaches')),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_personal_training_sessions_confirmed_by_id_users')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_personal_training_sessions_member_id_members')),
    sa.ForeignKeyConstraint(['package_id'], ['personal_training_packages.id'], name=op.f('fk_personal_training_sessions_package_id_personal_training_packages')),
    sa.ForeignKeyConstraint(['training_record_id'], ['training_records.id'], name=op.f('fk_personal_training_sessions_training_record_id_training_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_training_sessions'))
    )
    op.create_index(op.f('ix_personal_training_sessions_coach_id'), 'personal_training_sessions', ['coach_id'], unique=False)
    op.create_index(op.f('ix_personal_training_sessions_member_id'), 'personal_training_sessions', ['member_id'], unique=False)
    op.create_index(op.f('ix_personal_training_sessions_package_id'), 'personal_training_sessions', ['package_id'], unique=False)
    op.create_index(op.f('ix_personal_training_sessions_start_time'), 'personal_training_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_personal_training_sessions_status'), 'personal_training_sessions', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('refund_no', sa.String(length=50), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], name=op.f('fk_refunds_handled_by_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_no'), 'refunds', ['refund_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_refund_no'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_personal_training_sessions_status'), table_name='personal_training_sessions')
    op.drop_index(op.f('ix_personal_training_sessions_start_time'), table_name='personal_training_sessions')
    op.drop_index(op.f('ix_personal_training_sessions_package_id'), table_name='personal_training_sessions')
    op.drop_index(op.f('ix_personal_training_sessions_member_id'), table_name='personal_training_sessions')
    op.drop_index(op.f('ix_personal_training_sessions_coach_id'), table_name='personal_training_sessions')
    op.drop_table('personal_training_sessions')
    op.drop_index(op.f('ix_course_attendance_schedule_id'), table_name='course_attendance')
    op.drop_index(op.f('ix_course_attendance_member_id'), table_name='course_attendance')
    op.drop_index(op.f('ix_course_attendance_attended_at'), table_name='course_attendance')
    op.drop_table('course_attendance')
    op.drop_index(op.f('ix_personal_training_packages_status'), table_name='personal_training_packages')
    op.drop_index(op.f('ix_personal_training_packages_member_id'), table_name='personal_training_packages')
    op.drop_table('personal_training_packages')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_no'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_course_bookings_status'), table_name='course_bookings')
    op.drop_index(op.f('ix_course_bookings_schedule_id'), table_name='course_bookings')
    op.drop_index(op.f('ix_course_bookings_member_id'), table_name='course_bookings')
    op.drop_table('course_bookings')
    op.drop_index(op.f('ix_checkins_status'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_member_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_checkin_time'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_bracelet_no'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_card_transactions_transaction_type'), table_name='card_transactions')
    op.drop_index(op.f('ix_card_transactions_member_id'), table_name='card_transactions')
    op.drop_index(op.f('ix_card_transactions_member_card_id'), table_name='card_transactions')
    op.drop_table('card_transactions')
    op.drop_index(op.f('ix_training_records_record_date'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_member_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_member_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('member_profiles')
    op.drop_index(op.f('ix_member_followups_member_id'), table_name='member_followups')
    op.drop_table('member_followups')
    op.drop_index(op.f('ix_member_feedback_status'), table_name='member_feedback')
    op.drop_index(op.f('ix_member_feedback_member_id'), table_name='member_feedback')
    op.drop_table('member_feedback')
    op.drop_index(op.f('ix_member_cards_status'), table_name='member_cards')
    op.drop_index(op.f('ix_member_cards_member_id'), table_name='member_cards')
    op.drop_index(op.f('ix_member_cards_kind'), table_name='member_cards')
    op.drop_index(op.f('ix_member_cards_end_date'), table_name='member_cards')
    op.drop_index(op.f('ix_member_cards_card_no'), table_name='member_cards')
    op.drop_table('member_cards')
    op.drop_index(op.f('ix_campaign_registrations_mobile'), table_name='campaign_registrations')
    op.drop_index(op.f('ix_campaign_registrations_member_id'), table_name='campaign_registrations')
    op.drop_index(op.f('ix_campaign_registrations_campaign_id'), table_name='campaign_registrations')
    op.drop_table('campaign_registrations')
    op.drop_index(op.f('ix_bracelet_records_status'), table_name='bracelet_records')
    op.drop_index(op.f('ix_bracelet_records_member_id'), table_name='bracelet_records')
    op.drop_index(op.f('ix_bracelet_records_bracelet_no'), table_name='bracelet_records')
    op.drop_index(op.f('ix_bracelet_records_borrowed_at'), table_name='bracelet_records')
    op.drop_table('bracelet_records')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_index(op.f('ix_members_mobile'), table_name='members')
    op.drop_index(op.f('ix_members_member_no'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_course_schedules_status'), table_name='course_schedules')
    op.drop_index(op.f('ix_course_schedules_start_time'), table_name='course_schedules')
    op.drop_index(op.f('ix_course_schedules_course_id'), table_name='course_schedules')
    op.drop_table('course_schedules')
    op.drop_index(op.f('ix_coaches_name'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_mobile'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_staff_name'), table_name='staff')
    op.drop_index(op.f('ix_staff_mobile'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_notifications_title'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_login_logs_username'), table_name='login_logs')
    op.drop_table('login_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('role_menus')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_menus_path'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_marketing_campaigns_title'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_status'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_course_categories_name'), table_name='course_categories')
    op.drop_table('course_categories')
    op.drop_table('club_settings')
    op.drop_index(op.f('ix_card_types_name'), table_name='card_types')
    op.drop_index(op.f('ix_card_types_kind'), table_name='card_types')
    op.drop_table('card_types')
    op.drop_index(op.f('ix_business_hours_weekday'), table_name='business_hours')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
